// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'xxxx',
    appId: '1:1067272827533:web:c8301395267b9101d0e8c4',
    messagingSenderId: '1067272827533',
    projectId: 'photo-quest-c7c59',
    authDomain: 'photo-quest-c7c59.firebaseapp.com',
    storageBucket: 'photo-quest-c7c59.firebasestorage.app',
    measurementId: 'G-28072QH021',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'xxxx',
    appId: '1:1067272827533:android:db28ca5905ca9445d0e8c4',
    messagingSenderId: '1067272827533',
    projectId: 'photo-quest-c7c59',
    storageBucket: 'photo-quest-c7c59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'xxxx',
    appId: '1:1067272827533:ios:11779c4875dd26bdd0e8c4',
    messagingSenderId: '1067272827533',
    projectId: 'photo-quest-c7c59',
    storageBucket: 'photo-quest-c7c59.firebasestorage.app',
    iosBundleId: 'com.example.photoQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'xxxx',
    appId: '1:1067272827533:ios:11779c4875dd26bdd0e8c4',
    messagingSenderId: '1067272827533',
    projectId: 'photo-quest-c7c59',
    storageBucket: 'photo-quest-c7c59.firebasestorage.app',
    iosBundleId: 'com.example.photoQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'xxxx',
    appId: '1:1067272827533:web:cd31e4a420c0dc62d0e8c4',
    messagingSenderId: '1067272827533',
    projectId: 'photo-quest-c7c59',
    authDomain: 'photo-quest-c7c59.firebaseapp.com',
    storageBucket: 'photo-quest-c7c59.firebasestorage.app',
    measurementId: 'G-85BYK3J2R4',
  );
}
